server:
  port: 8761 # Default Eureka Server port

eureka:
  client:
    register-with-eureka: false # This server doesn't need to register itself
    fetch-registry: false       # It doesn't fetch other servers' registries

spring:
  application:
    name: eureka-server
